services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://testuser:testpassword@db:5432/testdb
    ports:
      - "8003:8000"
    command: >
      sh -c "sleep 10 && python setup.py && uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
